disabled_rules:
  - comment_spacing
  - force_cast
  - trailing_whitespace

  # SwiftLint is having issues with my Carthage frameworks, have to disable this even though
  # the rule isn't being violated

  - identifier_name

line_length: 150

identifier_name:
  excluded:
    - id

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

excluded:
  - Pods
  - Specs
