disabled_rules:
  - force_cast
  - trailing_whitespace

line_length: 150

identifier_name:
  excluded:
    - id

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

excluded:
  - Pods
  - Specs
