disabled_rules:
  - comment_spacing
  - force_cast
  - force_try
  - trailing_whitespace
  
line_length: 150

type_body_length:
  warning: 1000
  error: 1500

file_length:
  warning: 1000
  error: 1500

identifier_name:
  excluded:
    - id
  max_length:
    warning: 60
    error: 70
  min_length:
    error: 1

nesting:
  type_level:
    warning: 2

function_parameter_count:
  warning: 7

excluded:
  - Pods
  - Specs
  - IntegrationSpecs
